### ISSUE TITLE
execv return 0 and does not set errno on errors

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1335]
Look at #1334 to reproduce this bug

```
	/* difference from posix: execv return 0 and does not set errno on errors */
	if (optind < argc) {
		execv(argv[optind], argv+optind);
		printf("env: execv: No such command '%s'\n", argv[optind]);
		return -ENOENT;
	}
```

**Comment by Ahish9009** [comment]
Hi,
Could I work on this issue?

**Comment by Deryugin** [comment]
@Ahish9009 sure! Codestyle and git workflow can be found on wiki: https://github.com/embox/embox/wiki

**Comment by Deryugin** [comment]
A little more details on this issue (as it seems to be a bit more complicated than it seemed before).

This due to `vfork()` implementation. `vfork()` is kind of optimization when you want to do `fork()` just to `execv()` in the child process without actual duplication of all process resources. The first problem raises because we "disconnect" child from the parent too early, before checking that the command really exists, so instead of returning error code for `execv()` child process just exits with this code. The second problem is that `execv()` is not checking for return values of function that it uses, so it simply returns zero.

**Comment by Ahish9009** [comment]
Hi

Thanks for the additional information!

**Comment by Deryugin** [comment]
@Ahish9009 how is it going?

**Comment by Ahish9009** [comment]
Hi
I’ve been understanding the code base for most of the past days, have began working on this yesterday, will update soon.

**Comment by Ahish9009** [comment]
Hey
So if I am understanding what's happening correctly, the vfork implementation currently copies and saves register values, and then calls the vfork_start_child function. I'm not sure where it is calling this function from as it is defined in 3 places:
- vfork_exchanged
- vfork_none
- vfork_stop_parent
A little more clarity on this would be really helpful!

**Comment by anton-bondarev** [comment]
@Ahish9009 I think vfork_exchanged implementation is used in your template. You can check it if make a compilation mistake in src/compat/posix/proc/vfork_exchange.c
I think there are following lines in your ./conf/mods.config
```
	include embox.compat.posix.proc.vfork_exchanged
	include embox.compat.posix.proc.exec_exchanged
```
