### ISSUE TITLE
No output with sifive_u qemu 4.2.0

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#1653]
template: `riscv/qemu-sifive-u`
qemu:
```
$ qemu-system-riscv32 --version
QEMU emulator version 4.2.0
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

Run embox:
```
$ qemu-system-riscv32 -nographic -machine sifive_u -kernel embox
qemu-system-riscv32: warning: No -bios option specified. Not loading a firmware.
qemu-system-riscv32: warning: This default will change in a future QEMU release. Please use the -bios option to avoid breakages when this happens.
qemu-system-riscv32: warning: See QEMU's deprecation documentation for details.
```

And.. no more output here.

P.S. But works well with qemu 4.1.0.

**Comment by alexkalmuk** [comment]
But template `riscv/qemu` works on qemu 4.2.0.

**Comment by anton-bondarev** [comment]
@nastya-nizharadze As I understand qemu-system-riscv32 with -machine sifive_u version 4.1.0 has wrong address map?

**Comment by nastya-nizharadze** [comment]
In qemu version 4.1.0 for the sifive_u machine, the uart address was not the same as that specified in the documentation of the machine emulated by it. In qemu version 4.2.0, this issue has been fixed. After fixing this address in embox, another problem became clear: in qemu 4.2.0 for the sifive_u machine, smp cpus = 2 and it is impossible to do less, but I did not handle this situation, due to which the output was incorrect.
