### ISSUE TITLE
mips/qemu don't build with OpenLibm 

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#1886]
If enabele openlibm in mips/qemu
```
	//include embox.compat.libc.math_builtins
	include embox.compat.libc.math_openlibm
```
build fails
```
./build/base/obj/embox.o: In function `print_f':
src/compat/libc/include/ctype.h:(.text+0x5af00): undefined reference to `roundl'
src/compat/libc/include/ctype.h:(.text+0x5afe8): undefined reference to `roundl'
```

**Comment by puranjaymohan** [comment]
I want to work on this issue

**Comment by puranjaymohan** [comment]
@anton-bondarev Please tell me how to proceed with solving this issue. I am kind of stuck here.
Thanks

**Comment by Deryugin** [comment]
@puranjaymohan I think that problem is in `openlibm-0.7.0/src/Make.files`. For some reason `s_roundl.c` (which implements `roundl()`) is compiled only for `i387 amd64 aarch64` architectures. Looks like it can be solved the same way it was solved for arm (take a look at `embox/third-party/lib/openlibm/patch.txt`).

**Comment by anton-bondarev** [comment]
@puranjaymohan Have you reproduced the trouble?

I see in openlibm/patch.txt
```
+ifneq ($(filter $(ARCH),arm),)
+$(CUR_SRCS) += s_roundl.c
+endif
+
```

**Comment by puranjaymohan** [comment]
Hi @Deryugin Thanks for the insight, I have used the same method to solve it for mips. 

@anton-bondarev Yes I have reproduced the issue and also solved it now after your suggestions. A pull request has been created #1956.
Thanks
