### ISSUE TITLE
Wierd code in compat/posix/curses/curses.c

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#2405]
There is wierd code
```
	if (ch == '#') {
		ch = '#';
	}
```

https://github.com/embox/embox/blob/master/src/compat/posix/curses/curses.c#L74

**Comment by wawuwo** [comment]
Hi @anton-bondarev! It's been two years since this weird code fragment was discovered and it moved to another line https://github.com/embox/embox/blob/master/src/compat/posix/curses/curses.c#L86 since then. As I understand it is a do-nothing construct in any language and could be safely removed. Would it be OK if I prepare a patch to close the issue?

**Comment by anton-bondarev** [comment]
> As I understand it is a do-nothing construct in any language and could be safely removed. Would it be OK if I prepare a patch to close the issue?

@wawuwo Yes, sure
