### ISSUE TITLE
VMEM on IMX6

### ISSUE THREAD

**Issue by anton-bondarev** [embox/embox#968]
When you use commands its breake on an assert in do_map_region() 
`assert(!mmu_pte_present(pte + pte_idx)); `

**Comment by Deryugin** [comment]
As far as I know, the problem is that on system start whole RAM is mapped 1-to-1 (i.e. every virtual address corresponds to the same physical address). When you execute command, system allocates a chunk of memory and tries to map it...
And this is exactly what given `assert()` checks: the same virtual address is being mapped twice.
