### ISSUE TITLE
Implement ferror and friends

### ISSUE THREAD

**Issue by alexkalmuk** [embox/embox#997]
There is a bunch of functions (clearerr, feof, ferror, fileno) in POSIX that are used to check and reset stream status.

**Comment by MrSquanchee** [comment]
Hii @alexkalmuk I would like to work on this issue.

**Comment by alexkalmuk** [comment]
Hi, well, you can get a try.

**Comment by alexkalmuk** [comment]
I'd suggest you first to check whether these functions are not implemented yet.

**Comment by alexkalmuk** [comment]
> And stubs for the other functions ferror() , feof() and clearerr() are defined here.

So it looks like we should implement these three functions.

**Comment by MrSquanchee** [comment]
@alexkalmuk . I am a lil bit stuck here. I want to know whether the `stdio` file functions implement an error field in the `flags` variable of file_struct or not or the error resolution is solely done with `errno` variable. If not I would like to change the code of all the file IO functions a lil bit to accommodate for a file error field and the `EOF` field in the `flags` variable.
Am I thinking in the correct direction ??? Guidance Required.

**Comment by MrSquanchee** [comment]
>  or the error resolution is solely done with errno variable.
As far as I have seen this seems to be the most obvious implementation.

**Comment by alexkalmuk** [comment]
You can probably start with tests for these functions, and check how they work on Linux first. So after that, we will have a bunch of tests and will think about how to implements this in Embox.

**Comment by MrSquanchee** [comment]
I propose following changes and want your advise ....
1. I want to add following lines in file_struct.h or stdio.h (I really don't know)
`#define _IO_EOF_SEEN          0x0010`
`#define _IO_ERR_SEEN          0x0020`
To check for the EOF for `feof()` and ERR for `ferror()` and later clear them from `file->flags` in `clearerr()`.

2. I want to add error handling in [fflush.c](https://github.com/embox/embox/blob/master/src/compat/libc/stdio/fflush.c) because right now fflush doesn't tell whether the [lib_ob_forceflush](https://github.com/embox/embox/blob/master/src/compat/libc/stdio/fflush.c#L19) worked or not.

3. I want to change the behavior of [fread](https://github.com/embox/embox/blob/master/src/compat/libc/stdio/fread.c) when encountering an error. That is, returning the error with setting the the `_IO_EOF_SEEN` and `_IO_ERR_SEEN` fields in `file->flags`.

4. I want to add Similar functionalities in [fseek](https://github.com/embox/embox/blob/master/src/compat/libc/stdio/fseek.c) and [fwrite](https://github.com/embox/embox/blob/master/src/compat/libc/stdio/fwrite.c).

5. As other file IO functions like `fgetc`, `fgets`, `fputc`, `fputs` depend on the above functions, they will also be covered by `ferror` and `feof`.

What do you say fellow developer ??
:)

**Comment by alexkalmuk** [comment]
@MrSquanchee Let's start with feof and clearerr which clears only EOF flag :)

**Comment by alexkalmuk** [comment]
As I understand `feof` should return whether EOF flag is already set. How it can be tested? ILet's consider a simple regular file with one symbol - `a`.

```
f = fopen("a.txt", "r");
test_assert_equal(feof(f). 0);
test_assert_not_equal(fgetc(f). EOF);
test_assert_equal(feof(f). 0);
test_assert_equal(fgetc(f). EOF);
test_assert_not_equal(feof(f). 0);
fclose(f);
```

What do you think?

**Comment by alexkalmuk** [comment]
btw I think the changes you proposed may be good, but I would suggest to verify this only for `read`, without changing fflush, fseek, etc.

**Comment by MrSquanchee** [comment]
> I would suggest to verify this only for `read`, without changing fflush, fseek, etc.

Roger that ..... :)

**Comment by MrSquanchee** [comment]
I implemented all the functions and flags and put the flags in `file_struct.h`.
I don't know where to put this test file and how to run the test.
Would you describe the process a lil bit to me ??
I am a noobie when it comes to testing, so please bear with me.
